baseURL: https://saadjsct.gitlab.io/

languageCode: en-us
theme: "PaperMod"
title: "saadjsct.github.io"


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
ignoreFiles: "/posts/templates/*"

params:
  defaultTheme: light
  title: "Saad JSCT"
  homeInfoParams:
      Title: A Blog on The INTERNET! 🎉
      Content: |
        **I'm glad you found it here. Thanks for stopping by.**

        There isn't a lot here. There is nothing to consume, and nothing to consume you, nothing but the good old human communication of two siblings, comforting themselves in their way and life, in truth.


        - Although  I am calling it a Blog, it doesn't follow necessarily that everything here is a "Blog Post". I write here anything that doesn't fit the evanescence and pace of everyday conversations, or the noiseness of social media platforms.

        If you have any comments or thoughts to share, let's exchange emails about them on (saadjsct@gmail.com) "

  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"] 

  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  DateFormat: "January 2006"
  ShowShareButtons: true
  ShowReadingTime: true
  ShowWordCount: true

  cover:
    linkFullImages: true
    responsiveImages: true

# menu:
#   main:
    # - identifier: about
    #   name: About
    #   url: /about
    #   weight: 1
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 10
    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 20

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
  goldmark:
    renderer:
      unsafe: true
